### ISSUE TITLE
Location arguments not being parsed for negative latitudes

### ISSUE THREAD

**Issue by mechanicalturk8643** [sriyegna/Pikaptcha#14] opened 2016-08-23 07:29 UTC
If a negative is used in the latitude it fails to parse the arguments (instead showing the help message). Its probably related to it treating it as a command line flag.

**Comment by mlcmc** [comment] 2016-08-23 14:23
Reproducible and can't overcome using quotation marks.

**Comment by sriyegna** [comment] 2016-08-23 21:51
If you used quotation marks, the program doesn't have the code to parse it which is why it would fail.

**Comment by mlcmc** [comment] 2016-08-24 01:16
Even without quotation marks the issue is reproducible.

**Comment by sriyegna** [comment] 2016-08-24 01:39
Yes im aware of that. Its as mechanicalturk said. It treats it as a flag. I need to update it

**Comment by sriyegna** [comment] 2016-08-24 04:57
I really can't think of a way to combat this. Any suggestions? The only thing I can think of is making this run through python and actually calling the function. Using quotations doesn't seem to work, or maybe I did something wrong.

**Comment by mechanicalturk8643** [comment] 2016-08-24 05:27
Perhaps change the input format - check the last character in location[0] and location[1] is either N or S and E or W respectively. (setting a flag accordingly) Then chop off the last character, parse it as a float and multiply by flag.

**Comment by kiraacorsac** [comment] 2016-08-25 02:23
Actually, workaround would be: `pikaptcha -l " -2.0,2.0"`. Note the space after firs quotation mark.

**Comment by HeyItsJono** [comment] 2016-08-26 04:06
Or just `pikaptcha -l \-2.0,2.0` and parse out the `\` - that way it doesn't require quotation marks and is a little more obvious.

**Comment by skvvv** [comment] 2016-08-26 16:58
@sriyegna 

this should overcome it:
pikaptcha -l=-32.1231,22.3233
or perhaps this would be even better:
pikaptcha -l="-32.1231,22.3233"

haven't tested it though.

btw digging all these new additions :)

**Comment by sriyegna** [comment] 2016-09-08 21:49
Fixed in develop via GUI or through what kiraa mentioned about quotation's

**Closed as completed** 2016-09-08 21:49 UTC
Labels: bug
