### ISSUE TITLE
Failed to create user

### ISSUE THREAD

**Issue by TheMetaPirate** [sriyegna/Pikaptcha#30] opened 2016-08-28 13:48 UTC
I get constantly errors while trying to create a new user with 2capchta:

This run will cost you approximately: 0.003
Making account #1
Attempting to create user grestkukstroz:zadvossvift. Opening browser...
Step 1: Verifying age using birthday: 1980-08-12
Step 2: Entering account details
Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Solved captcha
Failed to create user: grestkukstroz
Attempting to create user rastprishspesk:zadvossvift. Opening browser...
Step 1: Verifying age using birthday: 1980-08-12
Step 2: Entering account details
Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Solved captcha
Failed to create user: rastprishspesk
Attempting to create user vochbronslor:zadvossvift. Opening browser...
Step 1: Verifying age using birthday: 1980-08-12

And on an on

**Comment by sriyegna** [comment] 2016-08-28 18:34
Yeah. Its caused by recaptcha returning no slot available. I don't check for that and I don't have the time in the next few days to implement the check.

**Comment by sriyegna** [comment] 2016-09-02 01:43
This is now fixed in develop branch. 
It is caused by setting your rate in 2captcha.com too low. Mine is set at the max to $1. I have seen it work at $0.75.

**Closed as completed by sriyegna** 2016-09-02 01:43 UTC
Labels: bug
